version: "3"
services:
  icoding-java:
    build:
      context: .
      dockerfile: Dockerfilehaha
    image: icoding-java-img
    depends_on:
      - redis
    ports:
      - "8001:8080"
  redis:
    image: redis:alpine




#搭建一个CICD流程，由自动化流程，直接将项目从github拉下来。docker-compose up即可
#声明式 compose.yml，解耦
#命令式 docker service create --name -p
#docker stack deploy -c com.yaml 提前把镜像构建出来
